Corrected how poolI was set and fetched in account-screen

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -56,7 +56,7 @@ workflows:
     - activate-ssh-key@4: {}
     - git-clone@8.1: {}
     - script@1:
-        title: "Install node-gyp globally"
+        title: Install node-gyp globally
         inputs:
         - content: |-
             #!/usr/bin/env bash
@@ -65,6 +65,9 @@ workflows:
     - yarn@0:
         inputs:
         - command: install
+    - set-java-version@1:
+        inputs:
+        - set_java_version: '17'
     - script@1:
         inputs:
         - content: |-
@@ -153,6 +156,10 @@ workflows:
     - yarn@0:
         inputs:
         - command: install
+    - npm@1:
+        inputs:
+        - command: run ensure:symlink
+        title: Ensure Symlink
     - script@1:
         inputs:
         - content: |-
@@ -247,6 +254,44 @@ workflows:
         - app_id: '1640008383'
         - team_name: 656TD8GM9B
         - bundle_id: land.fx.fotos
+  FxFotos Android:
+    description: |
+      Installs dependencies.
+
+      Next steps:
+      - Add tests to your project and configure the workflow to run them.
+      - Check out [Getting started with Expo apps](https://devcenter.bitrise.io/en/getting-started/getting-started-with-expo-apps.html).
+    steps:
+    - activate-ssh-key@4: {}
+    - git-clone@6: {}
+    - yarn@0:
+        inputs:
+        - command: install
+    - npm@1:
+        inputs:
+        - command: run ensure:symlink
+        title: Ensure Symlink
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            #set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit #successfully
+            #set -o pipefail
+            # debug log
+            set -x
+
+            # write your script here
+            sdkmanager --install "cmake;3.10.2.4988404"
+            yes | sdkmanager --licenses
+        title: Install CMake
+    - android-build@1:
+        inputs:
+        - variant: release
+        - module: app
+        - project_location: "$BITRISE_SOURCE_DIR/android"
+    - deploy-to-bitrise-io@2: {}
 meta:
   bitrise.io:
     stack: osx-xcode-14.3.x-ventura
